"""add yoga videos

Revision ID: 9579a831a845
Revises: 002
Create Date: 2026-09-06 19:47:39.243163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yoga_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('video_uri', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_uri', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yoga_videos_category'), 'yoga_videos', ['category'], unique=False)
    op.create_index(op.f('ix_yoga_videos_language'), 'yoga_videos', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yoga_videos_language'), table_name='yoga_videos')
    op.drop_index(op.f('ix_yoga_videos_category'), table_name='yoga_videos')
    op.drop_table('yoga_videos')
    # ### end Alembic commands ###
